# Generated by Django 4.2.1 on 2023-06-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='RatingAuthor',
            new_name='ratingAuthor',
        ),
    ]
